def common_pods
    pod 'Alamofire'
    pod 'RealmSwift'
end

def test_pods
    pod "Quick"
    pod "Nimble"
    pod "Nimble-Snapshots"
end

target 'CleanSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  common_pods

  target 'CleanSwiftTests' do
    inherit! :search_paths
    test_pods
  end
end
